### ISSUE TITLE
Add averageResult get-only property to Rollable

### ISSUE THREAD

**Issue by Samasaur1** [Samasaur1/DiceKit#16]
This is the third part of #7, which was ⅔ implemented in #15.

### What This is?

A computed property of type `Roll`.

#### Example Declaration:

```swift
extension Rollable {
    var averageResult: Roll { get }
}
```

#### Expected Results:

```swift
Die.d6.averageResult // 4 // 3.5 rounds to 4
Die(13)!.averageResult // 7
Dice(withModifier: 5).averageResult // 5
```

**Comment by Taufi** [comment]
I'll work on this.

**Comment by Samasaur1** [comment]
Thanks! Feel free to base your work off what is in the `possibility-and-probability` branch.
