### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by richardbmx** [Samasaur1/DiceKit#35]
Hi @Samasaur1 , I wanted to ask you if the dice are related to the project? that the name of the project is DICEKIT

It is to take references and start working on the logo that you have requested

**Comment by Samasaur1** [comment]
Hey @richardbmx! Yes, the dice are very important to the project. In fact, the main point of the project is to simulate dice. Again, this project's logo should have the 3 layer structure in multiple shades.

Thanks so much!

**Comment by richardbmx** [comment]
@Samasaur1  I present the proposal based on what was discussed and under your specifications with some improvements in the symmetry and text that make it more attractive visually

![logo1092](https://user-images.githubusercontent.com/35604837/46588316-36d2e300-ca68-11e8-9d2d-fa38f633feba.png)

Additional I present this second proposal that has a minimalist and more modern touch that represents your project for having the dice and be composed of the letters d and k fucionadas in a silhouette very nice to look at.

![logo1093](https://user-images.githubusercontent.com/35604837/46588569-929f6b00-ca6c-11e8-896a-892a396a48ce.png)

**Comment by Samasaur1** [comment]
@richardbmx These both look amazing! I like both the top and bottom logos, but Swift packages (which DiceKit is) use a three-layer image, so I'm going to have to use that as the main logo. I can use the bottom design as a secondary logo though.

If you don't mind sharing your files, I can add this amazing logo!

**Comment by richardbmx** [comment]
@Samasaur1  perfect no problem I'm going to put together the folder with all the files so you can use the logos.

**Comment by richardbmx** [comment]
Here I give you the link with all the necessary files to use the logo, inside you find different variations of the logo to be used in different applications as well as the original files to edit them if you need it. Any questions you can write me I am ready for next projects if you wish

[Google Drive] (https://drive.google.com/open?id=1-gzvWBtHIUquVOIcV0TzIDpRa0SqyV5K)
