### ISSUE TITLE
Check if number of rolls is greater than or equal to 1

### ISSUE THREAD

**Issue by paulpela** [Samasaur1/DiceKit#88]
https://github.com/Samasaur1/DiceKit/blob/d67f52f6d2b483180814644cd1d96edb97e060d1/Sources/DiceKit/Rollable.swift#L115

We should check whether the provided Int value is at least one. If you provide a `times` <= 0, then in the rest of the method we'll have an unhandled crash because we're force unwrapping possibly empty array, for example:

https://github.com/Samasaur1/DiceKit/blob/d67f52f6d2b483180814644cd1d96edb97e060d1/Sources/DiceKit/Rollable.swift#L131

**Comment by Samasaur1** [comment]
This is actually an even bigger problem, because it's _guaranteed_ to crash if `times <= 0`, one line 117, because it tries to create an invalid `Range`.

**Comment by Samasaur1** [comment]
Thanks for catching this!
